name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '17'
          github-token: ${{ secrets.XPIPE_GITHUB_TOKEN }}

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Publish
        run: ./gradlew publish
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: JReleaser
        run: ./gradlew jreleaserRelease
        env:
          XPIPE_GITHUB_TOKEN: ${{ secrets.XPIPE_GITHUB_TOKEN }}
          XPIPE_DISCORD_WEBHOOK: ${{ secrets.XPIPE_DISCORD_WEBHOOK }}
